import { GoogleAuthProvider, signInWithPopup } from 'firebase/auth';
import Head from 'next/head'
import { authentication } from '../firebase';
import { useRouter } from 'next/router';


export default function Home() {
  const router = useRouter();

	const signInWithGoogle = () => {
		const provider = new GoogleAuthProvider();
		signInWithPopup(authentication, provider)
			.then((result) => {
				console.log(result);
				router.push('/Home');
			})
			.catch((error) => {
				console.log(error);
			});
	};
	return (
		<div>
			<Head>
				<title>Lifter</title>
				<meta name="description" content="Generated by create next app" />
				<link rel="icon" href="/FB.ico" />
			</Head>
			<div className="flex flex-col justify-center items-center h-screen bg-[#FF00BF]">
				<p className="flex justify-center text-3xl font-bold text-white">
					Lifter
				</p>

				<div className="flex justify-center">
					<button
						className="text-xl text-black font-bold rounded-md bg-white px-16 py-2 m-5"
						onClick={signInWithGoogle}
					>
						Login
					</button>
				</div>
			</div>
		</div>
	);
}
